version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: todoapp

  backend:
    build: ./backend
    image: theleyn/tp-backend:v1.0 
    container_name: todo-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/todoapp

  frontend:
    build: ./frontend
    image: theleyn/tp-frontend:v1.0 
    container_name: todo-frontend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - backend
