name: GitHub Actions ToDoList

on: [push, workflow_dispatch]
jobs:
  build:
    name: Create build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v4
      
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: | 
          cd backend
          npm install
          cd ..
          cd frontend
          pip install -r requirements.txt
          cd ..
          echo "Install Completed"

  tests:
    name: ReBuild and Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v4
      
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: | 
          cd backend
          npm install
          cd ..
          cd frontend
          pip install -r requirements.txt
          cd ..
          echo "Install Completed"
      
      - name: launch Test
        run: pytest
  
  build-images:
    name: Build Docker Images
    # Ajouter tests
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v4

      - name: Run docker-compose
        run: docker-compose up -d

